#!/bin/bash
# This theme is for the Custom Cove script.  

# How to use:
# Change the names in the lines below to match the names of the theme
# style you want to use.

# Change gtktheme
xfconf-query -c xsettings -p /Net/ThemeName -s "Custom-cove"

## Change icon theme
xfconf-query -c xsettings -p /Net/IconThemeName -s "Obsidian-Red"

## Change openbox theme
#sed -i "s/$(grep "<theme>" ~/.config/openbox/rc.xml -A 5 | grep "<name>"| awk -F"[><]" '{print $3}')/"Custom-covebox"/g" ~/.config/openbox/rc.xml
xmlstarlet ed -L -N o="http://openbox.org/3.4/rc" -u '/o:openbox_config/o:theme/o:name' -v "Custom-covebox" ~/.config/openbox/rc.xml
openbox --reconfigure

## Change Geany theme
sed -i "s/color_scheme=.*/color_scheme=Cove.conf/g" ~/.config/geany/geany.conf

## Change jgmenu theme
if test -e ~/.config/jgmenu/backup; then
rm -fr ~/.config/jgmenu/backup
fi
#jgmenu_run gtktheme
jgmenu_run init --apply-obtheme

## Change xfce4-terminal theme
#xfce4-term-colors cove
xfconf-query -c xfce4-terminal -p /color-background -s "#2a2a36353838"
xfconf-query -c xfce4-terminal -p /color-foreground -s "#b8b8d7d7dbdb"
xfconf-query -c xfce4-terminal -p /color-palette -s "rgb(0,0,0);rgb(196,62,47);rgb(0,136,87);rgb(190,149,45);rgb(56,152,183);rgb(150,52,128);rgb(0,142,142);rgb(158,170,176);rgb(153,163,172);rgb(255,95,95);rgb(71,207,133);rgb(226,215,115);rgb(110,195,215);rgb(239,115,219);rgb(99,208,200);rgb(224,231,233)"

## Change Rofi theme
sed -i 's/^@theme "familiar.*/@theme "familiar-cove.rasi"/g' "$HOME/.config/rofi/themes/familiar/config.rasi"
sed -i 's/^@theme "rounded.*/@theme "rounded-cove.rasi"/g' "$HOME/.config/rofi/config.rasi"

# These lines are for the light/dark toggle and the custom toggle. Do not remove.
# Comment these lines in Custom-Theme or Light-Dark-Theme if copying a named theme.
rm -f ~/.cache/temp_theme
rm -f ~/.cache/custom_theme
