#!/bin/bash
# This theme is for the Custom Forge script.  

# How to use:
# Change the names in the lines below to match the names of the theme
# style you want to use.

# Change gtktheme
xfconf-query -c xsettings -p /Net/ThemeName -s "Custom-forge"

## Change icon theme
xfconf-query -c xsettings -p /Net/IconThemeName -s "Obsidian-Aqua"

## Change openbox theme
#sed -i "s/$(grep "<theme>" ~/.config/openbox/rc.xml -A 5 | grep "<name>"| awk -F"[><]" '{print $3}')/"Custom-forgebox"/g" ~/.config/openbox/rc.xml
xmlstarlet ed -L -N o="http://openbox.org/3.4/rc" -u '/o:openbox_config/o:theme/o:name' -v "Custom-forgebox" ~/.config/openbox/rc.xml
openbox --reconfigure

## Change Geany theme
sed -i "s/color_scheme=.*/color_scheme=Forge.conf/g" ~/.config/geany/geany.conf

## Change jgmenu theme
if test -e ~/.config/jgmenu/backup; then
rm -fr ~/.config/jgmenu/backup
fi
#jgmenu_run gtktheme
jgmenu_run init --apply-obtheme

## Change xfce4-terminal theme
#xfce4-term-colors forge
xfconf-query -c xfce4-terminal -p /color-background -s "#212125252b2b"
xfconf-query -c xfce4-terminal -p /color-foreground -s "#d3d3d8d8dbdb"
xfconf-query -c xfce4-terminal -p /color-palette -s "rgb(24,27,31);rgb(242,77,77);rgb(40,173,111);rgb(235,216,174);rgb(136,202,235);rgb(239,139,192);rgb(50,187,178);rgb(166,172,174);rgb(137,146,153);rgb(231,91,91);rgb(71,207,133);rgb(245,230,196);rgb(132,207,245);rgb(255,156,212);rgb(65,232,204);rgb(209,212,215)"

## Change Rofi theme
sed -i 's/^@theme "familiar.*/@theme "familiar-forge.rasi"/g' "$HOME/.config/rofi/themes/familiar/config.rasi"
sed -i 's/^@theme "rounded.*/@theme "rounded-forge.rasi"/g' "$HOME/.config/rofi/config.rasi"

# These lines are for the light/dark toggle and the custom toggle. Do not remove.
# Comment these lines in Custom-Theme or Light-Dark-Theme if copying a named theme.
rm -f ~/.cache/temp_theme
rm -f ~/.cache/custom_theme
