#!/bin/bash
# This theme is for the Custom Fane script.  

# How to use:
# Change the names in the lines below to match the names of the theme
# style you want to use.

# Change gtktheme
xfconf-query -c xsettings -p /Net/ThemeName -s "Custom-fane"

## Change icon theme
xfconf-query -c xsettings -p /Net/IconThemeName -s "Obsidian-Aqua"

## Change openbox theme
#sed -i "s/$(grep "<theme>" ~/.config/openbox/rc.xml -A 5 | grep "<name>"| awk -F"[><]" '{print $3}')/"Custom-fanebox"/g" ~/.config/openbox/rc.xml
xmlstarlet ed -L -N o="http://openbox.org/3.4/rc" -u '/o:openbox_config/o:theme/o:name' -v "Custom-fanebox" ~/.config/openbox/rc.xml
openbox --reconfigure

## Change Geany theme
sed -i "s/color_scheme=.*/color_scheme=Fane.conf/g" ~/.config/geany/geany.conf

## Change jgmenu theme
if test -e ~/.config/jgmenu/backup; then
rm -fr ~/.config/jgmenu/backup
fi
#jgmenu_run gtktheme
jgmenu_run init --apply-obtheme

## Change xfce4-terminal theme
#xfce4-term-colors fane
xfconf-query -c xfce4-terminal -p /color-background -s "#1d1d2b2b3333"
xfconf-query -c xfce4-terminal -p /color-foreground -s "#c5c5d4d4dbdb"
xfconf-query -c xfce4-terminal -p /color-palette -s "rgb(0,0,0);rgb(209,82,77);rgb(0,143,91);rgb(190,149,45);rgb(72,175,199);rgb(150,52,128);rgb(0,142,142);rgb(158,170,176);rgb(149,166,173);rgb(255,95,95);rgb(71,207,133);rgb(226,215,115);rgb(120,213,235);rgb(239,115,219);rgb(99,208,200);rgb(224,231,233)"

## Change Rofi theme
sed -i 's/^@theme "familiar.*/@theme "familiar-fane.rasi"/g' "$HOME/.config/rofi/themes/familiar/config.rasi"
sed -i 's/^@theme "rounded.*/@theme "rounded-fane.rasi"/g' "$HOME/.config/rofi/config.rasi"

# These lines are for the light/dark toggle and the custom toggle. Do not remove.
# Comment these lines in Custom-Theme or Light-Dark-Theme if copying a named theme.
rm -f ~/.cache/temp_theme
rm -f ~/.cache/custom_theme
