#!/bin/bash
#### A theme changer to set the theme to your own custom configuration.
### Simply change the "Lilidog" entries below with your own selections.

## Change gtktheme
xfconf-query -c xsettings -p /Net/ThemeName -s "Lilidog-Bright"

## Change icon theme
xfconf-query -c xsettings -p /Net/IconThemeName -s "Obsidian-Gray"

## Change openbox theme
#sed -i "s/$(grep "<theme>" ~/.config/openbox/rc.xml -A 5 | grep "<name>"| awk -F"[><]" '{print $3}')/"Lilidog-Brightbox"/g" ~/.config/openbox/rc.xml
xmlstarlet ed -L -N o="http://openbox.org/3.4/rc" -u '/o:openbox_config/o:theme/o:name' -v "Lilidog-Brightbox" ~/.config/openbox/rc.xml
openbox --reconfigure

## Change Geany theme
sed -i "s/color_scheme=.*/color_scheme=Lilidog-Bright.conf/g" ~/.config/geany/geany.conf

## Change jgmenu theme
#jgmenu_run gtktheme
if test -e ~/.config/jgmenu/backup; then
rm -fr ~/.config/jgmenu/backup
fi
jgmenu_run init --apply-obtheme

## Change xfce4-terminal theme
#xfce4-term-colors lilidog-bright
xfconf-query -c xfce4-terminal -p /color-background -s "#e6e6ebebebeb"
xfconf-query -c xfce4-terminal -p /color-foreground -s "#141412121212"
xfconf-query -c xfce4-terminal -p /color-palette -s "rgb(0,0,0);rgb(184,19,0);rgb(2,99,17);rgb(144,50,0);rgb(0,0,170);rgb(170,0,170);rgb(0,122,122);rgb(170,170,170);rgb(0,93,93);rgb(255,85,85);rgb(0,65,0);rgb(255,255,85);rgb(0,113,121);rgb(255,85,255);rgb(0,123,123);rgb(255,255,255)"

## Change Rofi theme
sed -i 's/^@theme "familiar.*/@theme "familiar-bright.rasi"/g' "$HOME/.config/rofi/themes/familiar/config.rasi"
sed -i 's/^@theme "rounded.*/@theme "rounded-bright.rasi"/g' "$HOME/.config/rofi/config.rasi"

# These lines are for the light/dark toggle and the custom toggle. Do not remove.
# Comment these lines in Custom-Theme or Light-Dark-Theme if copying a named theme.
rm -f ~/.cache/temp_theme
rm -f ~/.cache/custom_theme
